name: overflow_ai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0

  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.0
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  flutter_local_notifications: ^20.1.0
  cloud_firestore: ^6.1.2
  image_picker: ^1.2.1 
  http: ^1.6.0  
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  firebase_ai: ^3.8.0
  google_generative_ai: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true